language: node_js
node_js:
  - 9

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn lint
  - yarn test --coverage

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
